# Generated by Django 5.1.7 on 2025-04-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('can_publish_blogpost', 'Can publish blog post')], 'verbose_name': 'Блоговая запись', 'verbose_name_plural': 'Блоговые записи'},
        ),
    ]
